[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "alf"
version = "0.2.0"
description = "Peter's local computing companion"
requires-python = ">=3.11"
dependencies = [
    "rich",
    "sympy",
    "flask",
    "textual",
    "waitress",
    "rank-bm25",
    "trafilatura"
]

[project.scripts]
alf = "alf.main:main"

[tool.setuptools.package-data]
alf = [
    "identity.toml",
    "web/templates/*",
    "web/static/*",
    "web/static/jsmind/*",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
]

[tool.basedpyright]
typeCheckingMode = "off"
reportUnusedParameter = "none"
reportUnreachable = "none"
